INSERT INTO authors (autor_full_name, autor_description, autor_contact, autor_password) VALUES
('John Smith', 'American photographer focusing on nature and landscapes.', 'john@example.com', 'john123'),
('Maria Petrova', 'Contemporary artist specializing in abstract art.', 'maria@example.com', 'maria123'),
('Sofia Lee', 'Asian artist working in manga and anime style.', 'sofia@example.com', 'sofia123'),
('David Martinez', 'Spanish artist creating surrealist paintings.', 'david@example.com', 'david123'),
('Anna Kovalchuk', 'Ukrainian artist specializing in watercolor painting.', 'anna@example.com', 'anna123'),
('Julia Smirnova', 'Young Russian artist working in a modern style.', 'yulia@example.com', 'yulia123');

INSERT INTO paintings (p_name, p_img_link, p_description, p_price, category_id, autor_id) VALUES
('Sunset Over the Mountains', 'img/image01.png', 'A breathtaking view of the sunset over majestic mountains.', 200.00, 1, 1),
('Abstract Dreams', 'img/image01.png', 'Vibrant colors blend in this abstract masterpiece, evoking dreams and emotions.', 150.00, 2, 2),
('City Lights', 'img/image01.png', 'The bustling city at night, illuminated by a myriad of lights.', 180.00, 3, 3),
('Portrait of a Woman', 'img/image01.png', 'A striking portrait capturing the essence of a woman.', 250.00, 4, 4),
('Underwater World', 'img/image01.png', 'Explore the beauty of the ocean depths with this mesmerizing underwater scene.', 300.00, 5, 5),
('Manga Magic', 'img/image01.png', 'An enchanting manga artwork filled with magic and wonder.', 120.00, 6, 6),
('Surreal Landscape', 'img/image01.png', 'Journey through a surreal landscape where reality meets imagination.', 220.00, 7, 7),
('Watercolor Serenity', 'img/image01.png', 'Find peace and serenity in the gentle strokes of watercolor.', 170.00, 7, 7),
('Monochrome Memories', 'img/image01.png', 'A collection of black and white photographs capturing timeless memories.', 270.00, 1, 7),
('Urban Expression', 'img/image01.png', 'Expressive urban art depicting the raw energy of the city streets.', 190.00, 3, 7),
('Abstract Reflections', 'img/image01.png', 'Reflect upon the abstract forms and colors in this thought-provoking piece.', 160.00, 1, 7),
('Nature''s Symphony', 'img/image01.png', 'Harmony and beauty intertwine in this symphony of nature.', 210.00, 2, 1),
('Dreamy Waters', 'img/image01.png', 'Let your mind wander in the dreamy waters of this tranquil painting.', 230.00, 3, 2),
('Ethereal Elegance', 'img/image01.png', 'Elegance and grace captured in the ethereal beauty of this artwork.', 280.00, 4, 3),
('Whimsical Wonders', 'img/image01.png', 'Embark on a journey through whimsical wonders and enchanting scenes.', 260.00, 5, 4),
('Celestial Magic', 'img/image01.png', 'Experience the magic of the celestial realm in this captivating painting.', 320.00, 6, 5),
('Anime Adventures', 'img/image01.png', 'Join the characters on exciting adventures in this captivating anime artwork.', 140.00, 7, 6),
('Abstract Realms', 'img/image01.png', 'Explore the boundless realms of abstraction in this captivating piece.', 200.00, 3, 7),
('Watercolor Dreams', 'img/image01.png', 'Dive into a world of dreams and imagination with this vibrant watercolor.', 180.00, 3, 4),
('Vintage Visions', 'img/image01.png', 'Step back in time with these vintage photographs capturing bygone eras.', 290.00, 5, 3),
('Street Art Stories', 'img/image01.png', 'Each stroke tells a story in this vibrant street art composition.', 240.00, 5, 3),
('Abstract Echoes', 'img/image01.png', 'Echoes of abstraction resonate in this captivating artwork.', 170.00, 1, 7),
('Mystic Forest', 'img/image01.png', 'Enter the enchanted realm of the mystic forest and discover its secrets.', 310.00, 2, 1),
('Ocean Odyssey', 'img/image01.png', 'Embark on an epic odyssey across the vast expanse of the ocean.', 270.00, 3, 2),
('Fairy Tale Dreams', 'img/image01.png', 'Escape into a world of fairy tale dreams and fantastical landscapes.', 330.00, 4, 3),
('Galactic Gaze', 'img/image01.png', 'Peer into the depths of the galaxy with this mesmerizing cosmic gaze.', 350.00, 5, 4),
('Anime Wonderland', 'img/image01.png', 'Discover a wonderland filled with anime characters and magical creatures.', 160.00, 6, 5),
('Abstract Dimensions', 'img/image01.png', 'Journey through abstract dimensions in this captivating artwork.', 220.00, 7, 6),
('Watercolor Whispers', 'img/image01.png', 'Whispers of beauty resonate in this delicate watercolor painting.', 200.00, 5, 7),
('Retro Revival', 'img/image01.png', 'Revive the spirit of the past with these retro-inspired photographs.', 280.00, 5, 1),
('Graffiti Tales', 'img/image01.png', 'Each graffiti tells a tale of urban life and culture in this vibrant composition.', 250.00, 5, 1),
('Abstract Illusions', 'img/image01.png', 'Illusions come to life in this captivating abstract artwork.', 190.00, 2, 1),
('Enchanted Forest', 'img/image01.png', 'Wander through an enchanted forest filled with magic and mystery.', 300.00, 1, 4),
('Starlight Serenade', 'img/image01.png', 'Serenade under the starlight with this enchanting celestial painting.', 320.00, 2, 1),
('Deep Sea Dreams', 'img/image01.png', 'Dive deep into the dreams of the sea with this mesmerizing underwater scene.', 290.00, 3, 2),
('Fantasy Fables', 'img/image01.png', 'Explore fantastical fables and mythical creatures in this captivating artwork.', 340.00, 4, 3),
('Celestial Symphony', 'img/image01.png', 'Join the celestial symphony with this enchanting portrayal of the cosmos.', 360.00, 5, 4);